services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    depends_on:
      - postgres_db
    volumes:
      - ./src:/usr/src/app/src
  postgres_db:
    image: postgres:17
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: null
